# Generated by Django 4.2.2 on 2023-06-18 12:05

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juvenile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('juvenile_img', models.ImageField(upload_to=home.models.upload_juvenile_image)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('address', models.TextField()),
                ('missing', models.BooleanField(default=False)),
                ('missing_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_more_images)),
                ('juvenile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='more_images', to='home.juvenile')),
            ],
        ),
    ]
